### ISSUE TITLE
go get -u is broken when using modules

### ISSUE THREAD

**Issue by TankTheFrank** [go-gormigrate/gormigrate#22]
Using go1.11.2 darwin/amd64

Any 'go get -u' or 'go get -u ./...'  fails and stops with

```
go: github.com/go-gormigrate/gormigrate@v1.3.0: parsing go.mod: unexpected module path "gopkg.in/gormigrate.v1"
```

With verbose logging also adds
```
go: error loading module requirements
```

Regardless if I use "github.com/go-gormigrate/gormigrate" or "gopkg.in/gormigrate.v1" as import the result is the same.

**Comment by andreynering** [comment]
@TankTheFrank That's pretty strange. I suppose you're trying to use it as module instead of withing a GOPATH, right?

I personally haven't being using `go get -u` when using modules, and I'm not sure how that's supposed to work. Instead, I manually edit the `go.mod` file to fix the version I want to use. Maybe you should try that.

Let me know if you have more information.

**Comment by TankTheFrank** [comment]
Yes, I'm using go modules outside of gopath.

Turns out that it was a transitive dependency that was using the github path instead of gopkg.in. Using gopkg.in everywhere (as in absolutely everywhere - including all dependencies) works file.

**Comment by andreynering** [comment]
@TankTheFrank Thanks for the return.
