### ISSUE TITLE
Is a cli on the horizon?

### ISSUE THREAD

**Issue by frederikhors** [go-gormigrate/gormigrate#23]
Is a cli on the horizon?

Would be great to use it like:

`gormigrate -m` for all migrations

or

`gormigrate -m 201608301400`

or

`gormigrate -r 201608301400` for rollback

and so on...

**Comment by andreynering** [comment]
Hi @frederikhors,

Can you explain a bit more how do you see that working?

There are other tools out there that uses a cli to handle migrations, like [migrate](https://github.com/golang-migrate/migrate). They work because migrations are written in SQL instead of Go, so they can just read the `.sql` files and run them.

But with gormigrate migrations are written in Go, and a CLI wouldn't e able to run the code. You could expose the gormigrate functions as CLI commands of your app, though.

**Comment by andreynering** [comment]
As I said, I don't think a CLI fits this project, so I'll be closing this issue.

If anyone have any idea on how to implement such feature, let me know.
